use_frameworks!
inhibit_all_warnings!

platform :ios, '11.0'

target 'XYHelper_Example' do
  pod 'XYHelper', :path => '../'
  
  target 'XYHelper_Tests' do
    inherit! :search_paths
    
    
  end
end
